### ISSUE TITLE
Missing dependency in resource "aws_secretsmanager_secret_rotation" "rsm-sr"

### ISSUE THREAD

**Issue by cschwarze** [lgallard/terraform-aws-secrets-manager#24]
Error: error enabling Secrets Manager Secret "" rotation: ResourceNotFoundException: Secrets Manager can't find the specified secret.
│ 
│   with module.opensearch.module.secrets-manager.aws_secretsmanager_secret_rotation.rsm-sr["/aws/opensearch/newdomain/Prod/TestSecret3"],
│   on .terraform/modules/opensearch.secrets-manager/main.tf line 77, in resource "aws_secretsmanager_secret_rotation" "rsm-sr":
│   77: resource "aws_secretsmanager_secret_rotation" "rsm-sr" {

**Comment by lgallard** [comment]
Closed by #25
