### ISSUE TITLE
How to Retrieve secret binary from aws console

### ISSUE THREAD

**Issue by ArjunManojKumar** [lgallard/terraform-aws-secrets-manager#26]
While using [example [binary]](https://github.com/lgallard/terraform-aws-secrets-manager/tree/master/examples/binary),how are we supposed to retrieve the value?

![image](https://user-images.githubusercontent.com/110974600/203915157-32afcf2e-da9d-421c-95e6-61d0aa49895d.png)
![image](https://user-images.githubusercontent.com/110974600/203915259-322dc234-dcf6-4ef3-a883-1bc22852cc13.png)

While checking the AWS console, I am not seeing a binary option.
The output of my build : 

`Apply complete! Resources: 11 added, 0 changed, 0 destroyed.

Outputs:

rotation_enabled = false
secret_arns = {
  "secret-binary-205" = "arn:aws:secretsmanager:us-east-1:*******:secret:WANV-TEST-******"`

- Also if I need to upload the pem file as binary, how is it supposed to be done?

Thanks for your time

Thanks and Regards
Arjun Manoj Kumar

**Comment by lgallard** [comment]
@ArjunManojKumar this question is not related to the Terraform module. To retrieve the value use the AWS CLI as explained [here](https://serverfault.com/questions/1095060/how-to-retrieve-binary-file-from-aws-secrets-manager-using-aws-cli).

I'm going to close the issue as it's not related to the module.

**Comment by ArjunManojKumar** [comment]
@lgallard Thanks for the reply.
