### ISSUE TITLE
Bug "A reference to a resource type must be followed by at least one attribute access"

### ISSUE THREAD

**Issue by noamgreen** [lgallard/terraform-aws-secrets-manager#42]
last ver 0.10.0
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.23.1

'''
module "secrets-manager" {
  source                  = "lgallard/secrets-manager/aws"
  version = "0.10.0"

  secrets                 = {
                              "aws-key" = {
                                description = "aws-key ad-hoc password"
                                secret_key_value = {
                                  awsAccessKeyId = ""
                                  awsSecretKey = ""
                                }
                                recovery_window_in_days = 7
                              }
                            }
  tags                    = {
                              environment = var.env
                              region      = var.region
                              managed     = "terraform"
  }
}
'''

'''
│ Error: Invalid reference
│
│   on .terraform/modules/secrets-manager/main.tf line 22, in resource "aws_secretsmanager_secret_version" "sm-sv":
│   22:   secret_id     = aws_secretsmanager_secret.sm[index].arn
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
╵
╷
│ Error: Invalid reference
│
│   on .terraform/modules/secrets-manager/main.tf line 35, in resource "aws_secretsmanager_secret_version" "sm-svu":
│   35:   secret_id     = aws_secretsmanager_secret.sm[index].arn
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
╵
╷
│ Error: Invalid reference
│
│   on .terraform/modules/secrets-manager/main.tf line 64, in resource "aws_secretsmanager_secret_version" "rsm-sv":
│   64:   secret_id     = aws_secretsmanager_secret.rsm[index].arn
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
╵
╷
│ Error: Invalid reference
│
│   on .terraform/modules/secrets-manager/main.tf line 77, in resource "aws_secretsmanager_secret_version" "rsm-svu":
│   77:   secret_id     = aws_secretsmanager_secret.rsm[index].arn
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
╵
╷
│ Error: Invalid reference
│
│   on .terraform/modules/secrets-manager/main.tf line 93, in resource "aws_secretsmanager_secret_rotation" "rsm-sr":
│   93:   secret_id           = aws_secretsmanager_secret.rsm[index].arn
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
'''

in 0.9.0 all working 

Thansk

**Comment by lgallard** [comment]
@noamgreen thanks for reporting. Version 0.10.1 fixes this issue.
